name: Stargate-DHD
main: net.TheDgtl.StargateDHD.StargateDHD
version: 0.2.0
description: A DHD plugin for the Stargate plugin for the Bukkit plugin for Minecraft
author: Drakia
website: http://www.thedgtl.net